import React from 'react';
import Head from 'next/head';
import { Navbar, Main, About, Tech, Projects } from '../../components';

export default function Home() {
  return (
   <main>
    <Head>
      <title>Donna Wong | Full Stack Software Engineer</title>
      <meta name='description' content='generated by create next app' />
      <link rel='icon' href='/assets/logo.png' />
    </ Head>
    <div>
      <Navbar />
      <Main />
      <About />
      <Tech />
      <Projects />
    </div>
   </main>
  )
}