import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../../components/Navbar.jsx';

export default function Home() {
  return (
   <div>
    <Head>
      <title>Donna Wong | Full Stack Developer</title>
      <meta name='description' content='generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Navbar />
   </div>
  )
}
