import Head from 'next/head';
import Image from 'next/image';
import { Navbar, Main, About, Skills, Projects } from '../../components';

export default function Home() {
  return (
   <div>
    <Head>
      <title>Donna Wong | Full Stack Software Engineer</title>
      <meta name='description' content='generated by create next app' />
      <link rel='icon' href='/assets/navLogo.png' />
    </Head>
    <Navbar />
    <Main />
    <About />
    <Skills />
    <Projects />
   </div>
  )
}
